// src/component/GuitarList.tsx
import styled from 'styled-components';

import AnimateMount from '@/model/AnimateMount';
import {useStore} from '@/model/store';
import Guitar from './Guitar';

export default function GuitarList() {
	const guitars = useStore(s => s.guitars);

	return <div>
		{guitars.map((g, gtrIdx) =>
			<AnimateMount clsTrans='animate' key={g._id}>
				<DivGtrBlock>
					<Guitar guitarIndex={gtrIdx} guitar={g} />
				</DivGtrBlock>
			</AnimateMount>
		)}
	</div>;
}

const DivGtrBlock = styled.div`
	display: inline-block;
	vertical-align: top;
	margin: 0 10px 10px 0;

	transition: transform .4s, opacity .4s;
	transform: translateY(-100px);
	opacity: 0;
	&.animate {
		transform: translateY(0);
		opacity: 1;
	}
`;

// src/component/GuitarList.vue
<script setup lang="ts">
import useStore from '@/model/useStore';
import Guitar from './Guitar.vue';

const store = useStore();
</script>

<template>
	<transition-group name="guitars" tag="div">
		<div v-for="(g, idx) of store.guitars" :key="g._id" :class="m.gtrBlock">
			<Guitar :guitarIndex="idx" :guitar="g" />
		</div>
	</transition-group>
</template>

<style module="m" lang="scss">
	.gtrBlock {
		display: inline-block;
		vertical-align: top;
		margin: 0 10px 10px 0;
	}

	:global(.guitars-move),
	:global(.guitars-enter-active),
	:global(.guitars-leave-active) {
		transition: all .3s ease;
	}
	:global(.guitars-enter-from),
	:global(.guitars-leave-to) {
		opacity: 0;
	}
	:global(.guitars-leave-active) {
		position: absolute;
	}
</style>
