// src/component/Guitar.vue
<script setup lang="ts">
import store from '~/model/store';
import {IGuitar} from '~/model/types';
import Pack from './Pack.vue';
import Scale from './Scale.vue';
import StringRow from './StringRow.vue';
import Summation from './Summation.vue';
import Tuning from './Tuning.vue';

const props = defineProps<{
	guitarIndex: number;
	guitar: IGuitar;
}>();
</script>

<template>
	<div :class="[m.gtrBox, m['color' + props.guitarIndex % 7]]">
		<div :class="m.topRow">
			<div :class="m.name">Guitar #{{props.guitarIndex + 1}}</div>
			<div :class="m.topBtns">
				<button v-if="props.guitarIndex > 0"
					@click="() => store.moveLeft(props.guitar)"
					title="Move left">
					⇐
				</button>
				<button @click="() => store.remove(props.guitar)" title="Remove">✕</button>
			</div>
		</div>
		<div>
			<Scale :scale="props.guitar.scale"
				@update:scale="s => store.changeScale(props.guitar, s)" />
		</div>
		<div>
			<Pack :packName="props.guitar.packName"
				@update:packName="n => store.changePack(props.guitar, n)" />
		</div>
		<div :class="m.tuningSum">
			<Tuning :tuningName="props.guitar.tuningName"
				@update:tuningName="n => store.changeTuning(props.guitar, n)" />
			<Summation :guitar="props.guitar" />
		</div>
		<div :class="m.stringRow">
			<StringRow v-for="(s, strIdx) of props.guitar.strings"
				:key="s._id"
				:strIndex="strIdx"
				:str="s"
				:guitar="props.guitar" />
		</div>
	</div>
</template>

<style module="m">
	.gtrBox {
		padding: 2px 1px;
		border: 1px solid #ddd;
		&.color0 { border-top: 4px solid #36a2eb; }
		&.color1 { border-top: 4px solid #ff6384; }
		&.color2 { border-top: 4px solid #ff9f40; }
		&.color3 { border-top: 4px solid #ffcd56; }
		&.color4 { border-top: 4px solid #4bc0c0; }
		&.color5 { border-top: 4px solid #9966ff; }
		&.color6 { border-top: 4px solid #c9cbcf; }

		& > div {
			padding: 3px 6px;
		}
		.topRow {
			display: flex;
			gap: 6px;
			align-items: baseline;
			justify-content: space-between;
			.name {
				font-size: 115%;
			}
			.topBtns {
				display: flex;
				gap: 6px;
			}
		}
		.tuningSum {
			display: flex;
			justify-content: space-between;
			padding-right: 9px;
		}
		.stringRow {
			display: grid;
			grid-template-columns: repeat(4, auto);
		}
	}
</style>

// src/component/Guitar.tsx
import {memo} from 'react';
import styled from 'styled-components';

import {IGuitar} from '@/model/types';
import {useStore} from '@/model/store';
import Pack from './Pack';
import Scale from './Scale';
import StringRow from './StringRow';
import Summation from './Summation';
import Tuning from './Tuning';

interface Props {
	guitarIndex: number;
	guitar: IGuitar;
}

export default function Guitar(props: Props) {
	const moveLeft = useStore(s => s.moveLeft);
	const remove = useStore(s => s.remove);
	const changeScale = useStore(s => s.changeScale);
	const changePack = useStore(s => s.changePack);
	const changeTuning = useStore(s => s.changeTuning);

	return <DivGuitarBox $gtrIdx={props.guitarIndex % 7}>
		<DivTopRow>
			<DivName>Guitar #{props.guitarIndex + 1}</DivName>
			<DivTopButtons>
				{props.guitarIndex > 0 &&
					<button onClick={() => moveLeft(props.guitar)} title='Move left'>⇐</button>
				}
				<button onClick={() => remove(props.guitar)} title='Remove'>✕</button>
			</DivTopButtons>
		</DivTopRow>
		<div>
			<Scale scale={props.guitar.scale} onChange={s => changeScale(props.guitar, s)} />
		</div>
		<div>
			<Pack packName={props.guitar.packName} onChange={p => changePack(props.guitar, p)} />
		</div>
		<DivTuningSum>
			<Tuning tuningName={props.guitar.tuningName} onChange={t => changeTuning(props.guitar, t)} />
			<Summation guitar={props.guitar} />
		</DivTuningSum>
		<div>
			{props.guitar.strings.map((s, strIdx) =>
				<StringRow key={s._id} strIndex={strIdx} str={s} guitar={props.guitar} />
			)}
		</div>
	</DivGuitarBox>;
}

const DivGuitarBox = styled.div<{$gtrIdx: number}>`
	--color0: #36a2eb;
	--color1: #ff6384;
	--color2: #ff9f40;
	--color3: #ffcd56;
	--color4: #4bc0c0;
	--color5: #9966ff;
	--color6: #c9cbcf;
	padding: 2px 1px;
	border: 1px solid #ddd;
	border-top: 4px solid var(--color${p => p.$gtrIdx});
	& > div {
		padding: 3px 6px;
	}
`;
const DivTopRow = styled.div`
	display: flex;
	gap: 6px;
	align-items: baseline;
	justify-content: space-between;
`;
const DivName = styled.div`
	font-size: 115%;
`;
const DivTopButtons = styled.div`
	display: flex;
	gap: 6px;
`;
const DivTuningSum = styled.div`
	display: flex;
	justify-content: space-between;
	padding-right: 9px;
`;
