// src/component/Note.vue
<script setup lang="ts">
import {computed} from 'vue';
import {TNote} from '@/model/types';
import * as c from '@/model/consts';

const props = defineProps<{
	strIndex: number;
	note: TNote;
}>();
const emit = defineEmits<{
	'update:note': [note: TNote];
}>();

const note = computed({
	get: (): TNote => props.note,
	set: (note: TNote): void => emit('update:note', note),
});

const pitches = computed(() =>
	c.PITCHES_FOR_STRING.find(p => p.stringIndex === props.strIndex)!.pitches);
</script>

<template>
	<select v-model="note">
		<option v-for="pitch of pitches" :key="pitch.note" :value="pitch.note">
			{{pitch.note}} {{pitch.descr}}
		</option>
	</select>
</template>

// src/component/Note.tsx
import {useMemo} from 'react';
import * as c from '~/model/consts';
import {TNote} from '~/model/types';

interface Props {
	strIndex: number;
	note: TNote;
	onChange(n: TNote): void;
}

export default function Note(props: Props) {
	const pitches = useMemo(() =>
		c.PITCHES_FOR_STRING.find(p => p.stringIndex === props.strIndex)!.pitches,
	[props.strIndex]);

	return <select value={props.note} onChange={e => props.onChange(e.target.value as TNote)}>
		{pitches.map(pitch =>
			<option key={pitch.note} value={pitch.note}>
				{pitch.note} {pitch.descr}
			</option>,
		)}
	</select>;
}
