// src/component/StringRow.vue
<script setup lang="ts">
import {computed} from 'vue';
import {IGuitar, IString} from '@/model/types';
import store from '@/model/store';
import * as c from '@/model/consts';
import Gauge from './Gauge.vue';
import Pitch from './Pitch.vue';

const props = defineProps<{
	strIndex: number;
	str: IString;
	guitar: IGuitar;
}>();

const isModifGauge = computed((): boolean => {
	const pack = c.PACKS.find(p => p.name === props.guitar.packName)!;
	return pack.gauges[props.strIndex] === props.str.gauge;
});
const isModifNote = computed((): boolean => {
	const tuning = c.TUNINGS.find(t => t.name === props.guitar.tuningName)!;
	return tuning.notes[props.strIndex] === props.str.note;
});
</script>

<template>
	<div :class="m.stringRow">
		<div :class="m.strName">{{c.STRING_NAMES[props.strIndex]}}</div>
		<div :class="isModifGauge ? m.modifVal : m.origVal">
			<Gauge :gauge="props.str.gauge"
				@update:gauge="g => store.changeGauge(props.guitar, props.str, g)" />
		</div>
		<div :class="isModifNote ? m.modifVal : m.origVal">
			<Pitch :stringIndex="props.strIndex"
				:note="props.str.note"
				@update:note="n => store.changeNote(props.guitar, props.str, n)" />
		</div>
		<div>
			<input type="text" :class="m.tension" :value="props.str.tension.toFixed(2)" disabled />
			{{store.unit.value}}
		</div>
	</div>
</template>

<style module="m" lang="scss">
	.stringRow {
		display: flex;
		align-items: baseline;
		& > div {
			margin: 2px 3px;
			.tension {
				width: 3.5em;
				text-align: right;
			}
		}
		.strName {
			width: 26px;
		}
		.origVal {
			border: 1px solid red;
			padding: 1px;
		}
		.modifVal {
			border: 1px solid white;
			padding: 1px;
		}
	}
</style>

// src/component/StringRow.tsx
import {useMemo} from 'react';
import styled from 'styled-components';

import {IGuitar, IString} from '@/model/types';
import {useStore} from '@/model/store';
import * as c from '@/model/consts';
import Gauge from './Gauge';
import Note from './Note';

interface Props {
	strIndex: number;
	str: IString;
	guitar: IGuitar;
}

function StringRow(props: Props) {
	const unit = useStore(s => s.unit);
	const changeGauge = useStore(s => s.changeGauge);
	const changeNote = useStore(s => s.changeNote);

	const isModifGauge = useMemo(() => {
		const pack = c.PACKS.find(p => p.name === props.guitar.packName)!;
		return pack.gauges[props.strIndex] !== props.str.gauge;
	}, [props.guitar.packName, props.strIndex, props.str.gauge]);

	const isModifNote = useMemo(() => {
		const tuning = c.TUNINGS.find(t => t.name === props.guitar.tuningName)!;
		return tuning.notes[props.strIndex] !== props.str.note;
	}, [props.guitar.tuningName, props.strIndex, props.str.note]);

	return <DivStringRow>
		<DivStrName>{c.STRING_NAMES[props.strIndex]}</DivStrName>
		<DivModif $modif={isModifGauge}>
			<Gauge gauge={props.str.gauge} onChange={g => changeGauge(props.guitar, props.str, g)} />
		</DivModif>
		<DivModif $modif={isModifNote}>
			<Note strIndex={props.strIndex}
				note={props.str.note}
				onChange={n => changeNote(props.guitar, props.str, n)} />
		</DivModif>
		<div>
			<InputTension type='text' value={props.str.tension.toFixed(2)} disabled /> {unit}
		</div>
	</DivStringRow>;
}

export default StringRow;

const DivStringRow = styled.div`
	display: flex;
	align-items: baseline;
	& > div {
		margin: 2px 3px;
	}
`;
const DivStrName = styled.div`
	width: 26px;
`;
const InputTension = styled.input`
	width: 3.5em;
	text-align: right;
`;
const DivModif = styled.div<{$modif: boolean}>`
	border: 1px solid ${p => p.$modif ? 'red' : 'white'};
	padding: 1px;
`;
