// src/component/Summation.tsx
import styled from 'styled-components';
import {IGuitar} from '@/model/types';
import {useStore} from '@/model/store';

interface Props {
	guitar: IGuitar;
}

function Summation(props: Props) {
	const unit = useStore(s => s.unit);
	const sum = props.guitar.strings.reduce((accum, str) => accum + str.tension, 0);

	return <div>
		∑ <InputTension type='text' value={sum.toFixed(2)} disabled /> {unit}
	</div>;
}

export default Summation;

const InputTension = styled.input`
	width: 3.5em;
	text-align: right;
`;

// src/component/Summation.vue
<script setup lang="ts">
import {computed} from 'vue';
import {IGuitar} from '@/model/types';
import useStore from '@/model/useStore';

const props = defineProps<{
	guitar: IGuitar;
}>();

const store = useStore();

const sum = computed(() =>
	props.guitar.strings.reduce((accum, str) => accum + str.tension, 0),
);
</script>

<template>
	<div>∑ <input type="text" :class="m.tension" :value="sum.toFixed(2)" disabled />
		{{store.unit}}
	</div>
</template>

<style module="m" lang="scss">
	.tension {
		width: 3.5em;
		text-align: right;
	}
</style>
