// src/component/Unit.vue
<script setup lang="ts">
import {computed} from 'vue';
import {TUnit} from '@/model/types';
import useStore from '@/model/useStore';
import * as c from '@/model/consts';

const store = useStore();

const unit = computed({
	get: (): TUnit => store.unit,
	set: (u: TUnit): void => store.setUnit(u),
});
</script>

<template>
	<select v-model="unit">
		<option v-for="u of c.UNITS" :key="u.name" :value="u.name">
			unit: {{u.name}}
		</option>
	</select>
</template>

// src/component/Unit.tsx
import * as c from '~/model/consts';
import {TUnit} from '~/model/types';
import useStore from '~/model/useStore';

export default function Unit() {
	const store = useStore();

	return <select value={store.unit} onChange={e => store.setUnit(e.target.value as TUnit)}>
		{c.UNITS.map(u =>
			<option key={u.name} value={u.name}>
				unit: {u.name}
			</option>,
		)}
	</select>;
}
